---
- name: VMWareゲストの作成
  hosts: localhost
  connection: local
  gather_facts: False
   - vcinfo.yml
  vars:
   - myvmname: 'myvm'
   - mytemplate: 'rhel75-vmw-tpl'
   - mydc: 'DC01'
   - myds: 'Datastore'
   - mynetwork: 'VM Network'
   - myipaddr: '192.168.1.201'
   - mygateway: '192.168.1.1'
   - mycluster: 'Cluster01'
  tasks:

  - name: ゲスト作成(1つ) - 電源ONおよびIPアドレスアサインを待つ
    vmware_guest:
      validate_certs: no
      hostname: "{{ vchost }}"
      username: "{{ vcuser }}"
      password: "{{ vcpass }}"
      name: "{{ myvmname }}"
      template: "{{ mytemplate }}"
      datacenter: "{{ mydc }}"
      cluster: "{{ mycluster }}"
      state: poweredon
      wait_for_ip_address: yes
      folder: "/"
      disk:
        - size_gb: 4
          type: thin
          datastore: "{{ myds }}"
      networks: 
      - name: "{{ mynetwork }}"
#        gateway: "{{ mygateway }}"
#        ip: "{{ myipaddr }}"
#        netmask: 255.255.255.0
    register: myvm_facts

  - name: 作成したVM情報の表示
    debug:
      msg: "{{ myvm_facts }}"
